### ISSUE TITLE
Is the Wen 3417 Remote the same?

### ISSUE THREAD

**Issue by puterboy** [SebKuzminsky/ook-remote#1]
The Wen 3417 Air Filtration device seems to be a more powerful version of the Wen 3410 Air Filtration system.

Externally the remotes look identical.

I am asking because I would like to be able to control my Wen Air Filtration system via Home Assistant using Open MQTT Gateway esp32-based RTL433 decoder -- I already use it to read many other 433MHZ-based devices.

Any idea if it is compatible with RTL433 decoder project?

**Comment by SebKuzminsky** [comment]
No idea, sorry.
